# Generated by Django 5.0.6 on 2024-06-20 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='alt',
            new_name='avatar_alt',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='src',
            new_name='avatar_src',
        ),
    ]
