# Generated by Django 5.0.6 on 2024-06-27 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_product_views"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="limited",
            field=models.BooleanField(default=False),
        ),
    ]
