# Generated by Django 5.0.6 on 2024-07-06 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0009_sale"),
    ]

    operations = [
        migrations.RenameField(
            model_name="category",
            old_name="name",
            new_name="title",
        ),
        migrations.RenameField(
            model_name="subcategory",
            old_name="name",
            new_name="title",
        ),
    ]
